name: Build Kernel for sweet test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update, Upgrade and Install Packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
          libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig libssl-dev

    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: 'sajadasadollahi83/kernel_xiaomi_sweet_kewl'
        ref: 'lineage-21-ksu'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'kernel'

    - name: Clone PixelOS playground toolchain
      run: |
        git clone --quiet --depth=1 https://gitlab.com/PixelOS-Devices/playgroundtc.git -b 17 toolchain > /dev/null 2>&1
        echo "PATH=$(pwd)/toolchain/bin:/usr/lib/ccache:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(pwd)/toolchain/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Set up environment
      run: |
        echo "KBUILD_BUILD_USER=ventur" >> $GITHUB_ENV
        echo "KBUILD_BUILD_HOST=GitHub" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lyaml" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        cd kernel
        make O=out ARCH=arm64 sweet_user_defconfig
        make -j$(nproc) O=out ARCH=arm64 LLVM_IAS=1 CC="ccache clang" LD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: kernel/out/arch/arm64/boot/Image.gz-dtb
        
