name: Build Kewl Kernel for sweet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: 'sajadasadollahi83/kernel_xiaomi_sweet_kewl'
        ref: 'lineage-21-ksu'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          bc \
          ccache \
          clang \
          llvm \
          lld

    - name: Clone Toolchain
      run: |
        git clone --depth=1 https://gitlab.com/PixelOS-Devices/playgroundtc.git -b 17 toolchain

    - name: Set Environment Variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "KBUILD_BUILD_USER=ventur" >> $GITHUB_ENV
        echo "PATH=$(pwd)/toolchain/bin/:$PATH" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        make O=out ARCH=arm64 /vendor/sweet_user_defconfig
        make -j$(nproc) \
          O=out \
          ARCH=arm64 \
          LLVM_IAS=1 \
          CC="ccache clang" \
          LD=ld.lld \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-build
        path: |
          out/arch/arm64/boot/Image.gz-dtb
          out/arch/arm64/boot/dtbo.img
          
