name: Build Kewl Kernel for sweet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: 'sajadasadollahi83/kernel_xiaomi_sweet_kewl'
        ref: 'sajadasadollahi83-patch-2'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlayGround Clang 17 Toolchain
      run: |
        if [ ! -d "toolchain" ]; then
          git clone --depth=1 https://gitlab.com/PixelOS-Devices/playgroundtc -b 17 toolchain
        fi
        echo "PATH=$(pwd)/toolchain/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          bc \
          ccache

    - name: Set Environment Variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "KBUILD_BUILD_USER=ventur" >> $GITHUB_ENV
        echo "CC=ccache clang" >> $GITHUB_ENV
        echo "LD=ld.lld" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        make O=out ARCH=arm64 sweet_user_defconfig
        make -j$(nproc) \
          O=out \
          ARCH=arm64 \
          LLVM_IAS=1 \
          CC="ccache clang" \
          LD=ld.lld \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-build
        path: |
          out/arch/arm64/boot/Image.gz-dtb
          out
          
