name: Build Kernel for sweet test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Essential Packages for Kernel Building
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison

    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: 'sajadasadollahi83/kernel_xiaomi_sweet_kewl'
        ref: 'lineage-21-ksu'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'kernel'
        fetch-depth: 1

    - name: Clone PixelOS playground toolchain
      run: |
        git clone --quiet --depth=1 https://gitlab.com/PixelOS-Devices/playgroundtc.git -b 17 toolchain > /dev/null 2>&1
        echo "PATH=$(pwd)/toolchain/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(pwd)/toolchain/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Set up environment
      run: |
        echo "KBUILD_BUILD_USER=ventur" >> $GITHUB_ENV
        echo "KBUILD_BUILD_HOST=GitHub" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lyaml" >> $GITHUB_ENV

    - name: Clean Build Directory
      run: |
        cd kernel
        make O=out clean

    - name: Modify Kernel Config
      run: |
        cd kernel
        scripts/config --disable CONFIG_CC_STACKPROTECTOR_STRONG
        make O=out olddefconfig

    - name: Build Kernel
      run: |
        cd kernel
        make O=out ARCH=arm64 sweet_user_defconfig
        make -j$(nproc) O=out ARCH=arm64

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: kernel/out/arch/arm64/boot/Image.gz-dtb
        
