name: Build Kernel for sweet test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Essential Packages and Set Up GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9
        sudo update-alternatives --config gcc
        gcc --version

    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: 'sajadasadollahi83/kernel_xiaomi_sweet_kewl'
        ref: 'lineage-21-ksu'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'kernel'
        fetch-depth: 1

    - name: Set up environment
      run: |
        echo "KBUILD_BUILD_USER=ventur" >> $GITHUB_ENV
        echo "KBUILD_BUILD_HOST=GitHub" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lyaml" >> $GITHUB_ENV

    - name: Prepare Kernel Configuration
      run: |
        cd kernel
        make O=out clean
        make O=out olddefconfig

    - name: Build Kernel
      run: |
        cd kernel
        make O=out ARCH=arm64 sweet_user_defconfig
        make -j$(nproc) O=out ARCH=arm64

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: kernel/out/arch/arm64/boot/Image.gz-dtb
        
